%Function to synchronize photometry (PyPhotometry) and ephys/behavioral data (Intan).
%Inputs:
%   - digitalin.dat file generated by Intan software. If not provided,
%   default is digitalin.dat
%   - pyphotometry preprocessed data file. Generated with the
%   photometry_preprocessing script. 

%Returns:
%   - Matrix with photometry data and timestamps aligned to the ephys data (in s). 

function syncPhotometry = getSyncPhotometry(photometryData, intanData)
    if nargin < 2
        intanData = 'digitalin.dat'; % default name
    end
    format long

    %Extract barcode data from Intan file
    srIntan = 30000;
    m = memmapfile(intanData, 'Format', 'uint16', 'writable', false);
    digital_word2 = double(m.Data);
    clear m
    Nchan = 16;
    Nchan2 = 17;
    tester = zeros(length(digital_word2), Nchan);    
    for k = 1:Nchan
        tester(:, Nchan2-k) = (digital_word2 - 2^(Nchan-k)) >= 0;
        digital_word2 = digital_word2 - tester(:, Nchan2-k) * 2^(Nchan-k);
        barcode{Nchan2-k} = tester(:, Nchan2-k) == 1;
    end
    
    barcodeIntan = barcode{13}; %High/low signal

    %Extract barcode data from Pyphotometry preprocessed file
    %load(photometryData);
    srPhot = photometryData.sampling_rate; %Get samplingrate
    barcodePhot = photometryData.highLow; %High/low signal
    
    % Interpolation to match the sampling rate of barcodeIntan (130Hz-->30kHz)
    tPhot = (0:length(barcodePhot)-1) / double(srPhot); % photometry timestamps in s
    tIntan = (0:length(barcodeIntan)-1) / double(srIntan); % intan timestamps in s

    barcodePhotInterpolated = interp1(tPhot, double(barcodePhot), tIntan, 'linear', 'extrap');
    %barcodePhotInterpolated = interp1(tPhot, double(barcodePhot), tIntan, 'neares', 'extrap');

    % Cross correlation
    [xcorrValues, lags] = xcorr(double(barcodeIntan), barcodePhotInterpolated);
    [maxCorr, maxCorrIndex] = max(xcorrValues);
    maxLag = lags(maxCorrIndex); %lag between signals with higher correlation

    %Get sync photometry timestamps at 30kHz
    photTimestampsSr = (maxLag:length(barcodePhotInterpolated) + maxLag-1)'; % shiftet timestamps
    tPhotUs = photTimestampsSr/ srIntan;
    
    %Downsample back to 130Hz
    tPhotDs = tPhot + (maxLag/srIntan);
    dsTimestamps = interp1(tPhotUs, photTimestampsSr, tPhotDs, 'linear', 'extrap');
    dsTimestampsSec = dsTimestamps/double(srIntan); %in s
    syncPhotometry.sampling_rate = photometryData.sampling_rate;
    syncPhotometry.barcodesOn = photometryData.barcodesOn;
    syncPhotometry.barcodesOnOff = photometryData.barcodesOnOff;
    syncPhotometry.highLow = photometryData.highLow;
    syncPhotometry.timestamps = dsTimestampsSec';
    syncPhotometry.grabDA_z = photometryData.grabDA_z';
    syncPhotometry.grabDA_df = photometryData.grabDA_df';
    syncPhotometry.grabDA_raw = photometryData.grabDA_raw';
    %syncPhotometry = [dsTimestampsSec', photometryData.grabDA_z']; % can make z score or df/f
end
