%Function to synchronize photometry (PyPhotometry) and ephys/behavioral data (Intan).
%Inputs:
%   - digitalin.dat file generated by Intan software. If not provided,
%   default is digitalin.dat
%   - pyphotometry preprocessed data file. Generated with the
%   photometry_preprocessing script. 

%Returns:
%   - Matrix with photometry data and timestamps aligned to the ephys data (in s). 

function syncPhotometry = getSyncPhotometry_IZ(photometryData, intanData)
    if nargin < 2
        intanData = 'digitalin.dat'; % default name
    end
    format long

    %Extract barcode data from Intan file
    srIntan = 30000;
    m = memmapfile(intanData, 'Format', 'uint16', 'writable', false);
    digital_word2 = double(m.Data);
    clear m
    Nchan = 16;
    Nchan2 = 17;
    tester = zeros(length(digital_word2), 1);    
    digitalChan = 13;
    for k = Nchan2-digitalChan
        tester(:, Nchan2-k) = (digital_word2 - 2^(Nchan-k)) >= 0;
        digital_word2 = digital_word2 - tester(:, Nchan2-k) * 2^(Nchan-k);
        barcode{Nchan2-k} = tester(:, Nchan2-k) == 1;
    end
    
    barcodeIntan = barcode{13}; %High/low signal

    %Extract barcode data from Pyphotometry preprocessed file
    %load(photometryData);
    srPhot = photometryData.sampling_rate; %Get samplingrate
    barcodePhot = photometryData.highLow; %High/low signal
    
    % Resample barcodeIntan to match Photometry sampling rate (130 Hz)
    barcodeIntanResampled = resample(double(barcodeIntan), srPhot, srIntan);
    tIntanResampled = linspace(0, length(barcodeIntan) / srIntan, length(barcodeIntanResampled));

    tPhot = linspace(0, length(barcodePhot) / double(srPhot), length(barcodePhot));

    % Compute cross-correlation
    [xcorrValues, lags] = xcorr(double(barcodeIntanResampled), double(barcodePhot));
    [maxCorr, maxCorrIndex] = max(xcorrValues);
    maxLag = lags(maxCorrIndex); % Lag in samples at 130 Hz
    
    % Compute time shift
    timeShift = maxLag / double(srPhot); % Convert lag to time (seconds)

    %Shift photometry signal to match intan timestamps
    tPhotDs = tPhot + timeShift ;
    syncPhotometry.sampling_rate = photometryData.sampling_rate;
    syncPhotometry.barcodesOn = photometryData.barcodesOn;
    syncPhotometry.barcodesOnOff = photometryData.barcodesOnOff;
    syncPhotometry.highLow = photometryData.highLow;
    syncPhotometry.timestamps = tPhotDs';
    syncPhotometry.grabDA_z = photometryData.grabDA_z';
    syncPhotometry.grabDA_df = photometryData.grabDA_df';
    syncPhotometry.grabDA_raw = photometryData.grabDA_raw';
    %syncPhotometry = [dsTimestampsSec', photometryData.grabDA_z']; % can make z score or df/f
end
